#!/bin/bash
#/home/anthony/wsc/tests/files/lift_train.jsonl
python main.py --train_path '/home/anthony/wsc/data/train_xl.jsonl' --test_path '/home/anthony/wsc/data/debug.jsonl' -d --model_name='DirectTranslation' --ne=3
